
services:
  internship_project_node:
    build: .
    container_name: internship_project_container
    # Kendi Windows'undaki src klasörünü, container içindeki /project_ws/src klasörüne bağlıyoruz
    volumes:
      - ./src:/project_ws/src
      - ros2_build:/project_ws/build
      - ros2_install:/project_ws/install
      - ros2_log:/project_ws/log
    # Host ağı kullanarak ROS 2 DDS iletişimindeki gecikmeleri ve kısıtlamaları önlüyoruz
    network_mode: "host"
    environment:
      # Windows'taki X11 sunucusuna görüntü aktarımı için kritik ayar
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_DOMAIN_ID=0
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # Container'ın hemen kapanmaması için sonsuz bir döngüde bekletiyoruz
    command: tail -f /dev/null
    
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]

volumes:
  ros2_build:
  ros2_install:
  ros2_log: